local catppuccin = require("catppuccin")

-- Using catppuccin plugin as an engine and overwriting almost everything
catppuccin.setup({
  flavor = "mocha",
  custom_highlights = function(colors)
    return {
      -- General Text Editing
      Whitespace = { fg = colors.surface0 },
      NonText = { fg = colors.surface0 },
      -- Treesitter
      ["@type"] = { fg = colors.lavender },
      ["@struct"] = { fg = colors.lavender, bold = true },
      ["@type.builtin"] = { fg = colors.lavender },
      ["@type.definition"] = { fg = colors.lavender },
      ["@type.qualifier"] = { fg = colors.lavender },
      ["@type.reference"] = { fg = colors.lavender },
      ["@keyword"] = { fg = colors.teal },
      ["@keyword.modifier"] = { fg = colors.teal },
      ["@keyword.function"] = { fg = colors.teal },
      ["@keyword.coroutine"] = { fg = colors.teal },
      ["@keyword.conditional"] = { fg = colors.yellow, italic = true },
      ["@variable"] = { fg = colors.maroon },
      ["@variable.builtin"] = { fg = colors.sky },
      ["@variable.global"] = { fg = colors.sky },
      ["@variable.parameter"] = { fg = colors.pink },
      ["@variable.language"] = { fg = colors.maroon },
      ["@function"] = { fg = colors.sky },
      ["@function.call"] = { fg = colors.sky },
      ["@function.builtin"] = { fg = colors.sky },
      ["@function.macro"] = { fg = colors.sky },
      ["@method"] = { fg = colors.sky, italic = true },
      ["@constant"] = { fg = colors.yellow },
      ["@constant.builtin"] = { fg = colors.yellow },
      ["@constant.macro"] = { fg = colors.yellow },
      ["@enum"] = { fg = colors.mauve },
      ["@enumMember"] = { fg = colors.mauve },
      ["@field"] = { fg = colors.green },
      ["@property"] = { fg = colors.peach },
      ["@property.definition"] = { fg = colors.peach },
      ["@property.accessor"] = { fg = colors.peach },
      ["@parameter"] = { fg = colors.pink },
      ["@parameter.reference"] = { fg = colors.pink },
      ["@attribute"] = { fg = colors.yellow },
      ["@punctuation"] = { fg = colors.overlay1 },
      ["@punctuation.bracket"] = { fg = colors.overlay1 },
      ["@punctuation.delimiter"] = { fg = colors.overlay1 },
      ["@punctuation.special"] = { fg = colors.overlay1 },
      ["@comment"] = { fg = colors.overlay1, italic = true },
      ["@string"] = { fg = colors.green },
      ["@string.escape"] = { fg = colors.pink },
      ["@string.special"] = { fg = colors.peach },
      ["@number"] = { fg = colors.peach },
      ["@boolean"] = { fg = colors.pink },
      ["@operator"] = { fg = colors.teal },
      ["@operator.word"] = { fg = colors.teal },
      ["@annotation"] = { fg = colors.peach },
      ["@tag"] = { fg = colors.teal },
      ["@tag.attribute"] = { fg = colors.yellow },
      ["@text"] = { fg = colors.overlay1 },
      ["@text.diff.add"] = { fg = colors.green },
      ["@text.diff.delete"] = { fg = colors.red },
      ["@text.emphasis"] = { italic = true },
      ["@text.environment"] = { fg = colors.yellow },
      ["@text.environment.name"] = { fg = colors.peach },
      ["@text.literal"] = { fg = colors.green },
      ["@text.math"] = { fg = colors.teal },
      ["@text.reference"] = { fg = colors.pink },
      ["@text.strike"] = { strikethrough = true },
      ["@text.strong"] = { bold = true },
      ["@text.title"] = { fg = colors.mauve, bold = true },
      ["@error"] = { fg = colors.red, underline = true },
      ["@support"] = { fg = colors.teal },
      ["@support.function"] = { fg = colors.sky },
      ["@support.type"] = { fg = colors.lavender },
      ["@constructor"] = { fg = colors.lavender },
      ["@label"] = { fg = colors.pink },
      ["@namespace"] = { fg = colors.mauve },
      ["@repeat"] = { fg = colors.yellow },
      ["@storageclass"] = { fg = colors.yellow },
      ["@definition"] = { fg = colors.mauve },
      ["@implementation"] = { fg = colors.mauve },
      ["@identifier"] = { fg = colors.maroon },
      -- NvimTree
      NvimTreeNormal = { fg = colors.text, bg = colors.base },
      NvimTreeRootFolder = { fg = colors.text, bold = true },
      NvimTreeFolderName = { fg = colors.text },
      NvimTreeOpenedFolderName = { fg = colors.text },
      NvimTreeEmptyFolderName = { fg = colors.subtext1 },
      NvimTreeFolderIcon = { fg = colors.subtext1 },
      NvimTreeEmptyFolderIcon = { fg = colors.subtext1 },
      NvimTreeOpenedFile = { fg = colors.text },
      NvimTreeMarkdownFile = { fg = colors.text },
      NvimTreeImageFile = { fg = colors.text },
      NvimTreeExecFile = { fg = colors.yellow },
      NvimTreeSpecialFile = { fg = colors.rosewater },
      NvimTreeIndentMarker = { fg = colors.subtext1 },
      NvimTreeGitDirty = { fg = colors.blue },
      NvimTreeGitStaged = { fg = colors.teal },
      NvimTreeGitMerge = { fg = colors.peach },
      NvimTreeGitRenamed = { fg = colors.sky },
      NvimTreeGitNew = { fg = colors.green },
      NvimTreeGitDeleted = { fg = colors.maroon },
      NvimTreeGitIgnored = { fg = colors.subtext1 },
      NvimTreeSymlink = { fg = colors.peach },
      NvimTreeExecLink = { fg = colors.peach },
      --  Telescope
      TelescopeNormal = { fg = colors.text },
      TelescopeSelection = { fg = colors.text, bg = colors.surface1 },
      TelescopeSelectionCaret = { fg = colors.text },
      TelescopeMultiSelection = { fg = colors.text },
      TelescopeBorder = { fg = colors.subtext1 },
      TelescopePromptBorder = { fg = colors.subtext1 },
      TelescopeResultsBorder = { fg = colors.subtext1 },
      TelescopePreviewBorder = { fg = colors.subtext1 },
      TelescopeMatching = { fg = colors.yellow },
      TelescopePromptPrefix = { fg = colors.text },
      TelescopePrompt = { fg = colors.text },
      TelescopePromptSeparator = { fg = colors.subtext1 },
      TelescopePromptSelection = { fg = colors.text, bg = colors.surface1 },
      TelescopePromptTitle = { fg = colors.text },
      TelescopeResultsTitle = { fg = colors.text },
      TelescopeResultsSubTitle = { fg = colors.subtext1 },
      TelescopePreviewTitle = { fg = colors.text },
      TelescopePreviewSubTitle = { fg = colors.subtext1 },
      TelescopePreviewLine = { fg = colors.text },
      TelescopePreviewMatch = { fg = colors.yellow },
      TelescopePromptMatch = { fg = colors.yellow },
      -- Gitsigns
      GitSignsAdd = { fg = colors.green },
      GitSignsChange = { fg = colors.sky },
      GitSignsDelete = { fg = colors.maroon },
      GitSignsChangeDelete = { fg = colors.maroon },
    }
  end,
  color_overrides = {
    mocha = {
      -- Background layers
      base = "#12141A",
      mantle = "#15171D",
      crust = "#0B0B12",
      -- Accents
      rosewater = "#F5B8AB",
      flamingo = "#F5688E",
      pink = "#D19BDD",
      mauve = "#AB9DF2",
      red = "#f0706e",
      maroon = "#EB788B",
      peach = "#FC9867",
      yellow = "#EFDA7A",
      green = "#AED87E",
      teal = "#ABE2C9",
      sky = "#A8D8E6",
      sapphire = "#64b2e8",
      blue = "#78DCE8",
      lavender = "#AB9FEB",
      -- Foregrounds / overlays
      text = "#C6CAD7",
      subtext1 = "#A9AEC1",
      subtext0 = "#8E94AB",
      overlay2 = "#7D8296",
      overlay1 = "#676B80",
      overlay0 = "#464957",
      -- Surface layers
      surface2 = "#3A3D4A",
      surface1 = "#2F313D",
      surface0 = "#1D1E29",
    },
  },

  integrations = {
    treesitter = true,
    nvimtree = true,
    telescope = true,
    gitsigns = true,
  },
})

vim.cmd([[colorscheme catppuccin]])
